import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { createApp } from '../server.mjs';
import { pdfFixture } from './fixtures.mjs';

const dir = mkdtempSync(join(tmpdir(), 'study-companion-ui-'));
const { server, store } = createApp({ directory: dir, config: {} });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const output = resolve('test-results'); mkdirSync(output, { recursive: true });
let browser;
try {
  browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome', headless: true, args: ['--disable-gpu'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1040 } });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.goto(base); await page.getByRole('heading', { name: '让每一次理解，都有迹可循。' }).waitFor();
  await page.screenshot({ path: join(output, 'desktop-home.png'), fullPage: true });
  await page.getByRole('button', { name: '体验示例课件' }).click();
  await page.locator('#document-text').waitFor();
  assert.match(await page.locator('#document-text').textContent(), /The derivative/);
  await page.getByRole('button', { name: '保存选区' }).click();
  await page.locator('#note-title').fill('我的导数笔记');
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.modal'));
  await page.locator('[data-nav="notes"]').click();
  await page.getByRole('button', { name: /我的导数笔记/ }).waitFor();
  await page.getByRole('button', { name: /我的导数笔记/ }).click();
  await page.getByRole('button', { name: '编辑笔记' }).click();
  await page.locator('#note-content').fill('导数是函数的瞬时变化率。');
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.modal'));
  await page.locator('[data-nav="review"]').click();
  await page.getByRole('button', { name: '新建卡片' }).click();
  await page.locator('#card-question').fill('导数表示什么？'); await page.locator('#card-answer').fill('瞬时变化率。');
  await page.getByRole('button', { name: '加入复习' }).click();
  await page.getByRole('button', { name: '翻开答案' }).click();
  await page.getByRole('button', { name: /记住了/ }).click();
  await page.getByText('今天的复习完成了').waitFor();
  await page.locator('[data-nav="classroom"]').click();
  await page.getByRole('button', { name: '开始课堂' }).click();
  await page.locator('#session-title').fill('第 1 讲 · 导数'); await page.getByRole('button', { name: '开始记录', exact: true }).click();
  await page.getByRole('button', { name: '记个疑问' }).click(); await page.locator('#event-text').fill('怎样判断函数可导？');
  await page.getByRole('button', { name: '记入时间轴' }).click();
  await page.waitForFunction(() => !document.querySelector('.modal'));
  await page.getByText('怎样判断函数可导？', { exact: true }).waitFor();
  await page.getByRole('button', { name: '结束课堂' }).click();
  await page.getByRole('button', { name: '查看课后笔记' }).waitFor();
  await page.screenshot({ path: join(output, 'desktop-classroom.png'), fullPage: true });
  // 工作台：下拉选工具 → 该工具专属界面 → 信息流增删改查（始终显式选工具，不走关键词自动规划）
  await page.locator('[data-nav="workbench"]').click();
  await page.getByRole('heading', { name: '工作台' }).waitFor();
  await page.locator('#wb-tool').selectOption('calculator');
  await page.locator('[data-wb-key="7"]').click();
  await page.locator('[data-wb-key="×"]').click();
  await page.locator('[data-wb-key="6"]').click();
  await page.locator('[data-wb-key="="]').click();
  await page.waitForFunction(() => document.querySelector('#wb-calc-answer')?.textContent === '42');
  await page.getByRole('button', { name: '计算并记录' }).click();
  await page.getByRole('heading', { name: '学习结果' }).waitFor();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.modal'));
  assert.match(await page.locator('#wb-feed .wb-output').first().textContent(), /42/);
  const calculatorRuns = await page.locator('#wb-feed .run-row').count();
  await page.locator('#wb-feed .run-row').first().getByRole('button', { name: '删除' }).click();
  await page.waitForFunction(count => document.querySelectorAll('#wb-feed .run-row').length < count, calculatorRuns);
  await page.locator('#wb-tool').selectOption('save');
  await page.locator('#wb-title').fill('工作台笔记');
  await page.locator('#wb-input').fill('在工作台里保存的一段材料。');
  await page.getByRole('button', { name: '保存到笔记' }).click();
  await page.locator('#wb-feed').getByText('工作台笔记').first().waitFor();
  const noteRows = await page.locator('#wb-feed .run-row').count();
  await page.locator('#wb-feed .run-row').first().getByRole('button', { name: '编辑' }).click();
  await page.locator('#note-title').fill('工作台笔记 · 已改');
  await page.getByRole('button', { name: '保存笔记', exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.modal'));
  await page.locator('#wb-feed').getByText('工作台笔记 · 已改').waitFor();
  await page.locator('#wb-feed .run-row').first().getByRole('button', { name: '删除' }).click();
  await page.waitForFunction(count => document.querySelectorAll('#wb-feed .run-row').length < count, noteRows);
  await page.screenshot({ path: join(output, 'desktop-workbench.png'), fullPage: true });
  await page.locator('[data-nav="plugins"]').click();
  await page.getByRole('button', { name: '创建流程' }).click(); await page.locator('#workflow-name').fill('计算并归档');
  await page.locator('#workflow-step').selectOption('calculator'); await page.locator('#workflow-step').selectOption('save');
  await page.getByRole('button', { name: '保存流程' }).click();
  await page.getByRole('heading', { name: '计算并归档' }).waitFor();
  const card = page.locator('.workflow-card').filter({ has: page.getByRole('heading', { name: '计算并归档' }) });
  await card.getByRole('button', { name: '运行流程' }).click(); await page.locator('#run-input').fill('2 + 3 * 4');
  await page.locator('#run-form [type="submit"]').click();
  await page.getByRole('heading', { name: '学习结果' }).waitFor(); assert.match(await page.locator('.note-content').textContent(), /14/);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  // The native overlay delivers the selected tool as an event after bringing the app forward.
  await page.evaluate(() => { window.studyPendingOverlayAction = { tool: 'calculator', captureId: '' }; window.dispatchEvent(new Event('study-overlay-action')); });
  await page.getByRole('heading', { name: '随手拾起一个知识点' }).waitFor();
  assert.match(await page.locator('#capture-tool .capture-tool-trigger').textContent(), /计算器/);
  await page.locator('#capture-text').fill('6 * 7');
  await page.getByRole('button', { name: '处理文字' }).click();
  await page.getByRole('heading', { name: '学习结果' }).waitFor();
  assert.match(await page.locator('.note-content').textContent(), /42/);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.evaluate(() => { window.studyPendingOverlayAction = { tool: 'capture', captureId: '' }; window.dispatchEvent(new Event('study-overlay-action')); });
  await page.getByRole('heading', { name: '随手拾起一个知识点' }).waitFor();
  assert.match(await page.locator('#capture-tool .capture-tool-trigger').textContent(), /解释/);
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.locator('#mode-select').selectOption('exam');
  await page.waitForFunction(() => document.querySelector('#mode-select')?.value === 'exam' && !document.querySelector('.floating'));
  await page.locator('#mode-select').selectOption('study');
  await page.locator('.floating').waitFor();
  // A real uploaded PNG exercises pointer selection and the image context.
  const png = await page.evaluate(() => { const c = document.createElement('canvas'); c.width = 800; c.height = 400; const g = c.getContext('2d'); g.fillStyle = '#fff'; g.fillRect(0, 0, 800, 400); g.fillStyle = '#234'; g.font = '50px serif'; g.fillText('f(x) = x²', 80, 140); return c.toDataURL('image/png').split(',')[1]; });
  await page.locator('.nav [data-nav="library"]').click();
  const chooserPromise = page.waitForEvent('filechooser'); await page.getByRole('button', { name: '导入课件', exact: true }).click();
  await (await chooserPromise).setFiles({ name: 'formula.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') });
  await page.locator('#source-image').waitFor(); await page.waitForFunction(() => document.querySelector('#source-image')?.naturalWidth > 0);
  const box = await page.locator('#canvas-wrap').boundingBox();
  await page.mouse.move(box.x + 30, box.y + 20); await page.mouse.down(); await page.mouse.move(box.x + box.width * .65, box.y + box.height * .65, { steps: 8 }); await page.mouse.up();
  await page.getByAltText('已圈选的内容').waitFor();
  await page.screenshot({ path: join(output, 'desktop-selection.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-nav="home"]').first().click();
  await page.screenshot({ path: join(output, 'mobile-home.png'), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile must not overflow horizontally');
  await page.locator('.floating').click();
  await page.getByRole('heading', { name: '随手拾起一个知识点' }).waitFor();
  assert.match(await page.locator('#capture-tool .capture-tool-trigger').textContent(), /解释/);
  assert.ok(await page.locator('.capture-main-action').isVisible());
  assert.ok(await page.evaluate(() => {
    const select = document.querySelector('.capture-tool-card').getBoundingClientRect();
    const input = document.querySelector('#capture-text').getBoundingClientRect();
    const actions = document.querySelector('.capture-input-actions').getBoundingClientRect();
    const action = document.querySelector('.capture-main-action').getBoundingClientRect();
    return select.bottom < input.top && input.bottom < actions.top && actions.bottom < action.top && action.right <= window.innerWidth;
  }), 'capture cards must stay separated and within the mobile viewport');
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('#toast')).opacity) < .05);
  await page.screenshot({ path: join(output, 'mobile-capture-menu.png') });
  assert.ok(await page.locator('#capture-text').isVisible());
  await page.screenshot({ path: join(output, 'mobile-capture-inputs.png') });
  const tallCapture = await page.evaluate(() => {
    const canvas = document.createElement('canvas'); canvas.width = 1080; canvas.height = 2400;
    const g = canvas.getContext('2d'); g.fillStyle = '#fff'; g.fillRect(0, 0, canvas.width, canvas.height);
    g.fillStyle = '#182820'; g.font = '42px sans-serif'; g.fillText('微信小程序页面中的细字', 40, 120);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  const captureChooser = page.waitForEvent('filechooser');
  await page.getByRole('button', { name: '导入截图' }).click();
  await (await captureChooser).setFiles({ name: 'miniprogram.png', mimeType: 'image/png', buffer: Buffer.from(tallCapture, 'base64') });
  await page.getByRole('heading', { name: '圈选需要理解的区域' }).waitFor();
  await page.getByRole('button', { name: '保存到笔记' }).click();
  await page.locator('#note-content').waitFor();
  const savedCapture = await page.evaluate(async () => {
    const id = /\/api\/files\/([a-f0-9-]+)/.exec(document.querySelector('#note-content').value)?.[1];
    const response = await fetch('/api/files/' + id); const blob = await response.blob(); const bitmap = await createImageBitmap(blob);
    const result = { mime: blob.type, width: bitmap.width, height: bitmap.height }; bitmap.close(); return result;
  });
  assert.deepEqual(savedCapture, { mime: 'image/png', width: 1080, height: 2400 });
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await page.locator('.nav [data-nav="library"]').click();
  await page.getByRole('button', { name: /formula.png/ }).click();
  await page.getByAltText('formula.png', { exact: true }).waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile reader must not overflow');
  await page.screenshot({ path: join(output, 'mobile-reader.png'), fullPage: true });
  await page.locator('.nav [data-nav="library"]').click();
  const pdfChooser = page.waitForEvent('filechooser'); await page.getByRole('button', { name: '导入课件', exact: true }).click();
  await (await pdfChooser).setFiles({ name: 'derivatives.pdf', mimeType: 'application/pdf', buffer: pdfFixture() });
  await page.locator('#pdf-canvas').waitFor();
  await page.waitForFunction(() => document.querySelector('#pdf-canvas')?.width > 500);
  assert.match(await page.locator('#document-text').textContent(), /Learning derivatives/);
  await page.screenshot({ path: join(output, 'mobile-pdf.png'), fullPage: true });
  await page.setViewportSize({ width: 820, height: 1180 });
  await page.locator('[data-nav="plugins"]').click();
  await page.screenshot({ path: join(output, 'tablet-tools.png'), fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  const hashes = await page.evaluate(async () => {
    const { sha256Plain } = await import('/transport.js');
    const data = new Uint8Array(300000); for (let i = 0; i < data.length; i++) data[i] = i % 251;
    const plain = sha256Plain(data.buffer); const subtle = [...new Uint8Array(await crypto.subtle.digest('SHA-256', data))].map(x => x.toString(16).padStart(2, '0')).join('');
    return { known: sha256Plain(new TextEncoder().encode('abc').buffer), plain, subtle };
  });
  assert.equal(hashes.known, 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
  assert.equal(hashes.plain, hashes.subtle);
  const offlineContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const offlinePage = await offlineContext.newPage();
  offlinePage.on('pageerror', error => errors.push(error.message));
  offlinePage.on('dialog', dialog => dialog.accept());
  await offlinePage.goto(base); await offlinePage.getByRole('heading', { name: '让每一次理解，都有迹可循。' }).waitFor();
  await offlinePage.route('**/api/**', route => route.abort('internetdisconnected'));
  await offlinePage.locator('.nav [data-nav="notes"]').click();
  await offlinePage.getByRole('button', { name: '新建笔记' }).click();
  await offlinePage.locator('#note-title').fill('断网时的疑问');
  await offlinePage.locator('#note-content').fill('这一段在手机离线时写下。');
  await offlinePage.getByRole('button', { name: '保存笔记', exact: true }).click();
  await offlinePage.getByRole('button', { name: /断网时的疑问/ }).waitFor();
  // 断网新建后又在断网状态删除：创建操作尚未上传，应被撤销而不是同步时留下版本冲突
  await offlinePage.getByRole('button', { name: '新建笔记' }).click();
  await offlinePage.locator('#note-title').fill('断网删除测试');
  await offlinePage.locator('#note-content').fill('这条会在离线状态被删除。');
  await offlinePage.getByRole('button', { name: '保存笔记', exact: true }).click();
  await offlinePage.getByRole('button', { name: /断网删除测试/ }).waitFor();
  await offlinePage.locator('.nav [data-nav="workbench"]').click();
  await offlinePage.locator('#wb-tool').selectOption('save');
  await offlinePage.locator('#wb-feed .run-row').first().getByRole('button', { name: '删除' }).click();
  await offlinePage.waitForFunction(() => ![...document.querySelectorAll('#wb-feed h3')].some(h => h.textContent.includes('断网删除测试')));
  await offlinePage.locator('.nav [data-nav="settings"]').count();
  await offlinePage.getByRole('button', { name: '设置' }).click();
  await offlinePage.getByRole('button', { name: '连接与进度' }).click();
  await offlinePage.getByText('待连接', { exact: true }).waitFor();
  await offlinePage.unroute('**/api/**');
  await offlinePage.getByRole('button', { name: '立即同步' }).click();
  await offlinePage.getByText('已完成', { exact: true }).waitFor();
  const synced = await (await fetch(base + '/api/bootstrap')).json();
  assert.equal(synced.notes.filter(n => n.title === '断网时的疑问').length, 1);
  assert.equal(synced.notes.filter(n => n.title === '断网删除测试').length, 0);
  await offlineContext.close();
  const authDir = mkdtempSync(join(tmpdir(), 'study-companion-ui-auth-'));
  let consentRequired = false;
  const authApp = createApp({ directory: authDir, config: { ACCESS_TOKEN: 'browser-auth-secret-12345', CONTROL_ENABLED: 'true' }, tailnetAction: async action => {
    if (action === 'on' && consentRequired) throw new Error('Serve is not enabled on your tailnet. To enable, visit: https://login.tailscale.com/f/serve?node=TestNode123');
    return action === 'on' ? { url: 'https://study.example.ts.net' } : { off: true };
  } });
  await new Promise(resolve => authApp.server.listen(0, '127.0.0.1', resolve));
  try {
    const authBase = `http://127.0.0.1:${authApp.server.address().port}`;
    const authContext = await browser.newContext();
    const authPage = await authContext.newPage();
    authPage.on('pageerror', error => errors.push(error.message));
    await authPage.goto(authBase);
    await authPage.getByRole('heading', { name: '电脑管理员登录' }).waitFor();
    await authPage.locator('#login-token').fill('browser-auth-secret-12345');
    await authPage.getByRole('button', { name: '登录电脑工作站' }).click();
    await authPage.getByRole('heading', { name: '让每一次理解，都有迹可循。' }).waitFor();
    await authPage.getByRole('button', { name: '设置' }).click();
    await authPage.getByRole('button', { name: '打开服务控制台' }).click();
    await authPage.getByRole('dialog').getByRole('heading', { name: '电脑服务控制台' }).waitFor();
    await authPage.getByRole('button', { name: '关闭手机接入' }).click();
    await authPage.getByRole('button', { name: '开启手机接入' }).waitFor();
    await authPage.getByRole('button', { name: '开启手机接入' }).click();
    await authPage.getByRole('button', { name: '开启异网连接' }).click();
    await authPage.getByText('https://study.example.ts.net').waitFor();
    await authPage.getByRole('button', { name: '关闭异网连接' }).click();
    await authPage.getByRole('button', { name: '开启异网连接' }).waitFor();
    consentRequired = true;
    await authPage.getByRole('button', { name: '开启异网连接' }).click();
    const consentLink = authPage.getByRole('link', { name: 'Tailscale 官方授权页' });
    await consentLink.waitFor();
    assert.equal(await consentLink.getAttribute('href'), 'https://login.tailscale.com/f/serve?node=TestNode123');
    await authPage.getByRole('button', { name: '关闭', exact: true }).click();
    await authPage.getByRole('button', { name: '连接与进度' }).click();
    await authPage.getByRole('button', { name: '生成手机配对码' }).click();
    await authPage.getByText('一次性配对码：').waitFor();
    await authContext.close();
  } finally {
    await new Promise(resolve => authApp.server.close(resolve)); authApp.store.close();
    assert.ok(resolve(authDir).startsWith(resolve(tmpdir()) + sep)); rmSync(authDir, { recursive: true, force: true });
  }
  assert.deepEqual(errors, [], 'browser must not raise uncaught errors');
  console.log('PASS: desktop/mobile/tablet layout; document import; image selection; notes; card review; classroom timeline; workflow execution; mode switching; offline note sync; SHA-256 LAN fallback; admin login, service controls and pairing code.');
  console.log(`Screenshots: ${output}`);
} finally {
  await browser?.close(); await new Promise(resolve => server.close(resolve)); store.close();
  assert.ok(resolve(dir).startsWith(resolve(tmpdir()) + sep) && dir.includes('study-companion-ui-')); rmSync(dir, { recursive: true, force: true });
}
