plugins { id 'com.android.application' }
android {
    namespace 'cn.shizhi.study'
    compileSdk 34
    defaultConfig {
        applicationId 'cn.shizhi.study'
        minSdk 28
        targetSdk 34
        versionCode 7
        versionName '0.5.2'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { release { minifyEnabled false } }
}
dependencies { }
